CREATE TABLE "APPMANAGER"."USER_ROLE" (
  "USER_ID" NUMBER(20,0) NOT NULL,
  "ROLE_ID" NUMBER(20,0) NOT NULL,
  CONSTRAINT USER_ROLE_PK PRIMARY KEY (USER_ID,ROLE_ID),
  CONSTRAINT FK_APP_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID),
  CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;


INSERT INTO USER_ROLE VALUES (1,1);
INSERT INTO USER_ROLE VALUES (2,2);
