DROP TABLE "APPMANAGER"."APPLICATIONOWNER";
DROP SEQUENCE "APPMANAGER"."APPLICATIONOWNER_SEQ";
DROP TABLE "APPMANAGER"."APPLICATIONPRIV";
DROP SEQUENCE "APPMANAGER"."APPLICATIONPRIV_SEQ";
DROP TABLE "APPMANAGER"."APPROLEOWNER";
DROP SEQUENCE "APPMANAGER"."APPROLEOWNER_SEQ";
DROP TABLE "APPMANAGER"."APPROLEUSERVALUES";
DROP SEQUENCE "APPMANAGER"."APPROLEUSERVALUES_SEQ";
DROP TABLE "APPMANAGER"."APPUSERVALUES";
DROP SEQUENCE "APPMANAGER"."APPUSERVALUES_SEQ";
DROP TABLE "APPMANAGER"."ROLES_PRIV";
DROP SEQUENCE "APPMANAGER"."ROLES_PRIV_SEQ";
DROP TABLE "APPMANAGER"."PRIV";
DROP SEQUENCE "APPMANAGER"."PRIV_SEQ";
DROP TABLE "APPMANAGER"."ROLES";
DROP SEQUENCE "APPMANAGER"."ROLES_SEQ";
DROP TABLE "APPMANAGER"."APPLICATION";
DROP SEQUENCE "APPMANAGER"."APPLICATION_SEQ";


CREATE TABLE "APPMANAGER"."APPLICATION" 
(
    "APPLICATIONID" NUMBER NOT NULL,	
    "APP_HREF" VARCHAR2(512 BYTE), 
	"APP_SHORTNAME" VARCHAR2(256 BYTE), 
	"APP_LONGNAME" VARCHAR2(256 BYTE), 
	"APP_DESC" VARCHAR2(1024 BYTE), 
	"ACTIVEFLAG" NUMBER, 
	"LAST_UPDATE" TIMESTAMP (6), 
	"USERNAME" VARCHAR2(128 BYTE),
	"APP_ISINTRANETPUBLICFLAG" NUMBER, 
	"APP_HREF_LAUNCHMETHODID" NUMBER, 
	"APP_HREF_VERSION" NUMBER, 
	"HOSTFAMILYID" NUMBER, 
	"APP_USER_DESCRIPTION" VARCHAR2(1024 BYTE), 
	"APP_DEPARTMENTID" NUMBER, 
	"APP_TIMEOUTMIN" NUMBER, 
	"APP_ISESIGCLIENTFLAG" NUMBER,
	"FAMILYNAME" VARCHAR2(256 BYTE),
	CONSTRAINT APPLICATION_PK PRIMARY KEY (APPLICATIONID)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;

CREATE SEQUENCE  "APPMANAGER"."APPLICATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


CREATE TABLE "APPMANAGER"."APPLICATIONOWNER" 
(	
	"APPLICATIONOWNID" NUMBER NOT NULL,
    "APPLICATIONID" NUMBER,
    "OWNER" VARCHAR2(256),
    "FIRST_NAME" VARCHAR2(100),
    "LAST_NAME" VARCHAR2(100),
    "LAST_UPDATE" TIMESTAMP (6),
    "USERNAME" VARCHAR2(256),
    "ACTIVEFLAG" NUMBER,
	CONSTRAINT APPLICATIONOWNER_PK PRIMARY KEY (APPLICATIONOWNID),
	CONSTRAINT FK_APP_APPOWNER FOREIGN KEY (APPLICATIONID) REFERENCES APPLICATION(APPLICATIONID),
	CONSTRAINT UPPER_APPLICATIONOWNER CHECK (OWNER = UPPER(OWNER)),
	CONSTRAINT APPLICATIONOWNER_UNIQUE UNIQUE (APPLICATIONID,OWNER)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;
  
  
CREATE SEQUENCE  "APPMANAGER"."APPLICATIONOWNER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


CREATE TABLE "APPMANAGER"."APPLICATIONPRIV" 
(	
	"APPLICATIONPRIVID" NUMBER NOT NULL,
    "APPLICATIONID" NUMBER,
    "PRIV_NO" NUMBER,
    "LAST_UPDATE" TIMESTAMP (6),
    "USERNAME" VARCHAR2(256),
    "ACTIVEFLAG" NUMBER,
	CONSTRAINT APPLICATIONPRIV_PK PRIMARY KEY (APPLICATIONPRIVID),
	CONSTRAINT FK_APP_APPPRIV FOREIGN KEY (APPLICATIONID) REFERENCES APPLICATION(APPLICATIONID),
	CONSTRAINT APPLICATIONPRIV_UNIQUE UNIQUE (APPLICATIONID,PRIV_NO)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;
  


CREATE SEQUENCE  "APPMANAGER"."APPLICATIONPRIV_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "APPMANAGER"."APPROLEOWNER" 
(	
	"APPROLEOWNID" NUMBER NOT NULL,
    "APPLICATIONID" NUMBER,
    "ROLE_NO" NUMBER,
    "OWNER" VARCHAR2(256),
    "LAST_UPDATE" TIMESTAMP(6),
    "USERNAME" VARCHAR2(256),
    "ACTIVEFLAG" NUMBER,
    "FIRST_NAME" VARCHAR2(100),
    "LAST_NAME" VARCHAR2(100),
    CONSTRAINT APPROLEOWNER_PK PRIMARY KEY (APPROLEOWNID),
	CONSTRAINT FK_APP_APPROLEOWNER FOREIGN KEY (APPLICATIONID) REFERENCES APPLICATION(APPLICATIONID),
	CONSTRAINT UPPER_APPROLEOWNER CHECK (OWNER = UPPER(OWNER)),
	CONSTRAINT APPROLEOWNER_UNIQUE UNIQUE (APPLICATIONID,ROLE_NO,OWNER)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;
  

CREATE SEQUENCE  "APPMANAGER"."APPROLEOWNER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "APPMANAGER"."APPUSERVALUES" 
(	
	"APPUSERVALUEID" NUMBER NOT NULL,
    "APPUSERVALUESOURCE" VARCHAR2(256),
    "APPUSERVALUESOURCELOCATION" VARCHAR2(256),
    "APPUSERVALUEFIELDNAME" VARCHAR2(256),
    "APPUSERVALUETITLE" VARCHAR2(256),
    "LAST_UPDATE" TIMESTAMP(6),
    "USERNAME" VARCHAR2(256),
    "ACTIVEFLAG" NUMBER,
    CONSTRAINT APPUSERVALUES_PK PRIMARY KEY (APPUSERVALUEID),
    CONSTRAINT APPUSERVALUES_UNIQUE_FIELDNAME UNIQUE (APPUSERVALUEFIELDNAME)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;

CREATE SEQUENCE  "APPMANAGER"."APPUSERVALUES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "APPMANAGER"."PRIV" 
(	
	"PRIV_NO" NUMBER NOT NULL,
    "PRIV_ID" VARCHAR2(256),
    "PRIV_DPT" VARCHAR2(256),
    "PRIV_URL" VARCHAR2(256),
    "PRIV_DESC" VARCHAR2(256),
    "PRIV_DESC_EXT" VARCHAR2(256),
    "PRIV_SHOWMENU" CHAR(1),
    "ISFORCEDREDIRECT" NUMBER,
    "LAST_UPDATE" TIMESTAMP (6),
    "USERNAME" VARCHAR2(256),
    "ACTIVEFLAG" NUMBER,
    CONSTRAINT PRIV_PK PRIMARY KEY (PRIV_NO),
    CONSTRAINT UPPER_PRIV_ID CHECK (PRIV_ID = UPPER(PRIV_ID)),
    CONSTRAINT PRIV_UNIQUE_PRIV_ID UNIQUE (PRIV_ID)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;

CREATE SEQUENCE  "APPMANAGER"."PRIV_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "APPMANAGER"."ROLES" 
(	
	"ROLE_NO" NUMBER NOT NULL,
    "ROLETYPEID" NUMBER,
    "ROLE_ID" VARCHAR2(256) NOT NULL,
    "ROLE_DESC" VARCHAR2(256),
    "ROLE_DESC_EXT" VARCHAR2(512),
    "APP_ACCESSREQUESTMETHODID" NUMBER,
    "LAST_UPDATE" TIMESTAMP (6),
    "USERNAME" VARCHAR2(256),
    "ACTIVEFLAG" NUMBER,
    CONSTRAINT ROLES_PK PRIMARY KEY (ROLE_NO),
    CONSTRAINT UPPER_ROLE_ID CHECK (ROLE_ID = UPPER(ROLE_ID)),
    CONSTRAINT ROLES_UNIQUE_ROLE_ID UNIQUE (ROLE_ID)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;

CREATE SEQUENCE  "APPMANAGER"."ROLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "APPMANAGER"."ROLES_PRIV" 
(	
	"ROLES_PRIV_NO" NUMBER NOT NULL,
    "ROLE_NO" NUMBER,
    "PRIV_NO" NUMBER,
    "LAST_UPDATE" TIMESTAMP(6),
    "USERNAME" VARCHAR2(256),
    "ACTIVEFLAG" NUMBER,
    CONSTRAINT ROLES_PRIV_PK PRIMARY KEY (ROLES_PRIV_NO),
    CONSTRAINT FK_ROLES_PRIV_ROLES FOREIGN KEY (ROLE_NO) REFERENCES ROLES(ROLE_NO),
    CONSTRAINT FK_ROLES_PRIV_PRIV FOREIGN KEY (PRIV_NO) REFERENCES PRIV(PRIV_NO),
    CONSTRAINT ROLES_PRIV_UNIQUE UNIQUE (ROLE_NO,PRIV_NO)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;

CREATE SEQUENCE  "APPMANAGER"."ROLES_PRIV_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


CREATE TABLE "APPMANAGER"."APPROLEUSERVALUES" 
(	
	"ID" NUMBER NOT NULL,
    "APPUSERVALUEID" NUMBER,
    "APPLICATIONID" NUMBER NOT NULL,
    "LAST_UPDATE" TIMESTAMP(6),
    "USERNAME" VARCHAR2(256),
    "ACTIVEFLAG" NUMBER,
    "ROLE_NO" NUMBER NOT NULL,
    "PRIV_NO" NUMBER NOT NULL,
    CONSTRAINT APPROLEUSERVALUES_PK PRIMARY KEY (ID),
    CONSTRAINT FK_APP_APPLICATIONPRIV FOREIGN KEY (APPLICATIONID,PRIV_NO) REFERENCES APPLICATIONPRIV(APPLICATIONID,PRIV_NO),
	CONSTRAINT FK_APP_ROLES_PRIV FOREIGN KEY (PRIV_NO,ROLE_NO) REFERENCES ROLES_PRIV(PRIV_NO,ROLE_NO),
    CONSTRAINT APPROLEUSERVALUES_UNIQUE UNIQUE (APPLICATIONID,PRIV_NO,ROLE_NO,APPUSERVALUEID)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;
  

CREATE SEQUENCE  "APPMANAGER"."APPROLEUSERVALUES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;





    

  
