CREATE TABLE "APPMANAGER"."ROLE" (
  "ID" NUMBER(20,0) NOT NULL,
  "DESCRIPTION" VARCHAR(64) DEFAULT NULL,
  "NAME" VARCHAR(20) DEFAULT NULL,
  CONSTRAINT ROLE_PK PRIMARY KEY (ID)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;

INSERT INTO ROLE VALUES (1,'Administrator role (can edit Users)','ROLE_ADMIN');
INSERT INTO ROLE VALUES (2,'Default role for all Users','ROLE_USER');

CREATE SEQUENCE  "APPMANAGER"."ROLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
