DROP TABLE "APPMANAGER"."USER_ROLE";

DROP TABLE "APPMANAGER"."ROLE";
DROP SEQUENCE "APPMANAGER"."ROLE_SEQ";

DROP TABLE "APPMANAGER"."APP_USER";
DROP SEQUENCE "APPMANAGER"."APP_USER_SEQ";

CREATE TABLE "APPMANAGER"."APP_USER" (
  "ID" NUMBER(20,0) NOT NULL,
  "ACCOUNT_EXPIRED" CHAR NOT NULL,
  "ACCOUNT_LOCKED" CHAR NOT NULL,
  "ADDRESS" VARCHAR2(150) DEFAULT NULL,
  "CITY" VARCHAR2(50) DEFAULT NULL,
  "COUNTRY" VARCHAR2(100) DEFAULT NULL,
  "POSTAL_CODE" VARCHAR2(15) DEFAULT NULL,
  "PROVINCE" VARCHAR2(100) DEFAULT NULL,
  "CREDENTIALS_EXPIRED" CHAR NOT NULL,
  "EMAIL" VARCHAR2(255) NOT NULL,
  "ACCOUNT_ENABLED" CHAR DEFAULT NULL,
  "FIRST_NAME" VARCHAR2(50) NOT NULL,
  "LAST_NAME" VARCHAR2(50) NOT NULL,
  "PASSWORD" VARCHAR2(255) NOT NULL,
  "PASSWORD_HINT" VARCHAR2(255) DEFAULT NULL,
  "PHONE_NUMBER" VARCHAR2(255) DEFAULT NULL,
  "USERNAME" VARCHAR2(50) NOT NULL,
  "VERSION" NUMBER(11, 0) DEFAULT NULL,
  "WEBSITE" VARCHAR2(255) DEFAULT NULL,
  CONSTRAINT APP_USER_PK PRIMARY KEY (ID),
  CONSTRAINT APP_USER_UNIQUE_EMAIL UNIQUE (EMAIL),
  CONSTRAINT APP_USER_UNIQUE_USERNAME UNIQUE (USERNAME)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;

INSERT INTO APP_USER VALUES (-2,'0','0','','Denver','US','80210','CO','0','matt@raibledesigns.com','1','Matt','Raible','d033e22ae348aeb5660fc2140aec35850c4da997','Not a female kitty.','','admin',1,'http://raibledesigns.com');
INSERT INTO APP_USER VALUES (-1,'0','0','','Denver','US','80210','CO','0','matt_raible@yahoo.com','1','Tomcat','User','12dea96fec20593566ab75692c9949596833adc9','A male kitty.','','user',1,'http://tomcat.apache.org');

CREATE SEQUENCE  "APPMANAGER"."APP_USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "APPMANAGER"."ROLE" (
  "ID" NUMBER(20,0) NOT NULL,
  "DESCRIPTION" VARCHAR(64) DEFAULT NULL,
  "NAME" VARCHAR(20) DEFAULT NULL,
  CONSTRAINT ROLE_PK PRIMARY KEY (ID)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;

INSERT INTO ROLE VALUES (-1,'Administrator role (can edit Users)','ROLE_ADMIN');
INSERT INTO ROLE VALUES (-2,'Default role for all Users','ROLE_USER');

CREATE SEQUENCE  "APPMANAGER"."ROLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "APPMANAGER"."USER_ROLE" (
  "USER_ID" NUMBER(20,0) NOT NULL,
  "ROLE_ID" NUMBER(20,0) NOT NULL,
  CONSTRAINT USER_ROLE_PK PRIMARY KEY (USER_ID,ROLE_ID),
  CONSTRAINT FK_APP_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID),
  CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "APPMANAGER" ;


INSERT INTO USER_ROLE VALUES (-1,-2);
INSERT INTO USER_ROLE VALUES (-2,-1);
